---
title: "hw2_zh2493"
output: github_document
---

```{r warning = FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
```

## P1
## Read and clean the Mr. Trash Wheel sheet:

```{r warning = FALSE}
wheel_sheet = 
  read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx", range = "A2:N408", sheet = "Mr. Trash Wheel") %>%
  na.omit(dumpster) %>%
  janitor::clean_names() %>%
  mutate(sports_balls = round(as.numeric(sports_balls)))
```

## Read and clean precipitation data for 2018 and 2019

```{r warning = FALSE}
precipitation2018 = 
  read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2018 Precipitation", range = "A2:B14") %>%
  na.omit(wheel_sheet,  Precipitation) %>%
  janitor::clean_names() %>%
  mutate(year = "2018") %>%
  select(year, month, total)
  
precipitation2019 = 
  read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2019 Precipitation", range = "A2:B14") %>%
  na.omit(wheel_sheet,  Precipitation) %>%
  janitor::clean_names() %>%
  mutate(year = "2019") %>%
  select(year, month, total)

precipitation_2018_2019 = 
  combine(precipitation2018, precipitation2019) %>%
  mutate(month = month.name[month])

```

## P2
## First

```{r}
poly = 
  read.csv("./fivethirtyeight_datasets./pols-month.csv") %>%
  separate(mon, into = c("year", "month", "day")) %>%
  mutate(month = month.name[as.numeric(month)]) %>%
  janitor::clean_names() %>%
  mutate(year = as.numeric(year)) %>%
  pivot_longer(prez_gop:rep_dem, names_to = "president", values_to = "num") %>%
  mutate(month = substring(month, 0, 3)) %>%
  filter(president != "prez_dem" & president != "prez_gop") %>%
  select(-"day")

```


## Second
```{r}
snp = 
  read.csv("./fivethirtyeight_datasets./snp.csv") %>%
  janitor::clean_names() %>%
  mutate(date,date = lubridate::mdy(date)) %>%
  separate(date, into = c("year", "month", "day")) %>%
  mutate(month = month.name[as.numeric(month)]) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(year = ifelse(year>2049, year - 100, year)) %>%
  select(year, month, everything()) %>%
  select(-"day") %>%
  mutate(month = substring(month, 0, 3))

```

## Third
```{r}
unemployment = 
  read.csv("./fivethirtyeight_datasets./unemployment.csv") %>%
  pivot_longer(Jan:Dec, names_to = "month", values_to = "num") %>%
  janitor::clean_names() %>%
  select(year, month, everything()) %>%
  mutate(year = as.numeric(year))
```

## join
```{r}
merge_df = left_join(poly,snp, by = c("year", "month"))
merge_df = left_join(merge_df,unemployment, by = c("year", "month"))
  

```

